{{- if and ( eq (index .Values "cnvrg-cap").dbs.pg.enabled false) (( index .Values "cnvrg-operator").enabled)  }}
{{- $mypass := (lookup "v1" "Secret" "cnvrg" "cnvrg-production-pguser-cnvrg") }}
apiVersion: v1
kind: Secret
metadata:
  name: pg-creds-pgo
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
type: Opaque
data:
#  {{- $secretObj := (lookup "v1" "Secret" "cnvrg" "cnvrg-production-pguser-cnvrg") | default dict }}
#  {{- $secretData := (get $secretObj "data" | default dict) }}
#  {{- $jwtSecret := (get $secretData "password") }}
  POSTGRES_PASSWORD: {{ $mypass.data.password }}
  POSTGRESQL_ADMIN_PASSWORD: {{ $mypass.data.password }}
  POSTGRESQL_PASSWORD: {{ $mypass.data.password }}
{{- end }}
