{{- if and ( eq (index .Values "cnvrg-cap").dbs.pg.enabled false) (( index .Values "cnvrg-operator").enabled)  }}
{{- $pgosecret := (lookup "v1" "Secret" .Release.Namespace "cnvrg-production-pguser-cnvrg" | default dict) }}
apiVersion: v1
kind: Secret
metadata:
  name: pg-creds
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": post-install
type: Opaque
data:
  POSTGRES_DB: {{ $pgosecret.data.dbname }}
  POSTGRES_PASSWORD: {{ $pgosecret.data.password }}
  POSTGRES_USER: {{ $pgosecret.data.user }}
  POSTGRES_HOST: {{ $pgosecret.data.host }}
{{- end }}
